# Generated by Django 5.2.6 on 2025-09-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('movie_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('actor1_name', models.CharField(max_length=100)),
                ('actor2_name', models.CharField(blank=True, max_length=100)),
                ('director_name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi')], max_length=20)),
                ('release_year', models.PositiveIntegerField()),
            ],
        ),
    ]
